
server:
  port: 8761
eureka:
  client:
    # \u662F\u5426\u8981\u6CE8\u518C\u5230\u5176\u4ED6Eureka Server\u5B9E\u4F8B
    register-with-eureka: false
    # \u662F\u5426\u8981\u4ECE\u5176\u4ED6Eureka Server\u5B9E\u4F8B\u83B7\u53D6\u6570\u636E
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/